# -*- coding: utf-8 -*-
"""mapillary_streetscapes_lux_city.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I62B2CXltKEwOsvwfXgMMIWHDhU0Ym29
"""

# Installs the package.
!pip install mapillary

import mapillary.interface as mly
import requests
import json

token = 'MLY|25517726937837208|3f8625861dba933ed6b04631405be5bd'

mly.set_access_token(token)

import json
import os
import time
import requests

ACCESS_TOKEN = os.environ.get("MLY|25517726937837208|3f8625861dba933ed6b04631405be5bd")  # set this in your environment
if not ACCESS_TOKEN:
    raise RuntimeError("Set MAPILLARY_TOKEN environment variable first.")

headers = {"Authorization": f"OAuth {ACCESS_TOKEN}"}  # Mapillary auth style :contentReference[oaicite:2]{index=2}

with open("luxembourg_city.json", "r") as f:
    data = json.load(f)

os.makedirs("images", exist_ok=True)

for i, feat in enumerate(data["features"]):
    image_id = feat["properties"]["id"]

    # Ask Graph API for the fields you need
    fields = "thumb_2048_url,thumb_1024_url"
    meta_url = f"https://graph.mapillary.com/{image_id}?fields={fields}"
    meta = requests.get(meta_url, headers=headers)
    meta.raise_for_status()
    meta = meta.json()

    img_url = meta.get("thumb_2048_url") or meta.get("thumb_1024_url")
    if not img_url:
        print(f"[{i}] {image_id}: no thumb url (keys={list(meta.keys())})")
        continue

    img = requests.get(img_url)
    img.raise_for_status()

    out_path = os.path.join("images", f"{image_id}.jpg")
    with open(out_path, "wb") as out:
        out.write(img.content)

    if i % 100 == 0:
        print(f"Downloaded {i}/{len(data['features'])}")

    time.sleep(0.05)  # be polite

# Get image points close to Luxembourg
# The latitude of Luxembourg City, Luxembourg is 49.611622, and the longitude is 6.131935
data = mly.get_image_close_to(longitude=6.131935, latitude=49.611622).to_dict()

# Save the data as JSON
file_name = "luxembourg_city.json"
with open(file_name, mode="w") as f:
    json.dump(data, f, indent=4)

with open("luxembourg_city.json", "r") as f:
  data = json.load(f)

print(type(data))
print(data.keys())
feature = data["features"][0]
print(feature.keys())
print(feature["properties"].keys())

print(len(data["features"]))
print(data["features"][0]["properties"]["id"])

import pprint
pprint.pprint(data)

import json
import os
import time
import requests

ACCESS_TOKEN = "MLY|25517726937837208|3f8625861dba933ed6b04631405be5bd"
headers = {"Authorization": f"OAuth {ACCESS_TOKEN}"}

with open("luxembourg_city.json", "r") as f:
    data = json.load(f)

os.makedirs("images", exist_ok=True)

for i, feat in enumerate(data["features"], start=1):
    image_id = str(feat["properties"]["id"])

    # 1) get thumbnail urls
    meta = requests.get(
        f"https://graph.mapillary.com/{image_id}?fields=thumb_2048_url,thumb_1024_url",
        headers=headers,
        timeout=30
    )
    meta.raise_for_status()
    meta = meta.json()

    img_url = meta.get("thumb_2048_url") or meta.get("thumb_1024_url")
    if not img_url:
        print(f"[{i}] {image_id}: no thumbnail url")
        continue

    # 2) download image
    img = requests.get(img_url, timeout=60)
    img.raise_for_status()

    out_path = os.path.join("images", f"{image_id}.jpg")
    with open(out_path, "wb") as out:
        out.write(img.content)

    if i % 100 == 0:
        print(f"Downloaded {i}/{len(data['features'])}")

    time.sleep(0.05)  # polite

import os, json

saved = set(f.split(".")[0] for f in os.listdir("/content/images"))

with open("luxembourg_city.json", "r") as f:
    data = json.load(f)

missing = [
    feat["properties"]["id"]
    for feat in data["features"]
    if str(feat["properties"]["id"]) not in saved
]

print("Missing:", len(missing))
missing[:10]

!zip -r luxembourg_images.zip /content/images
from google.colab import files
files.download("luxembourg_images.zip")